language: clojure

services:
  - docker

jobs:
  include:
    - stage: build
      script: make install
    -
      script: make lint
    -
      script: make analyze

    - stage: test
      script: make test

after_success:
- CLOVERAGE_VERSION=1.0.10 make coverage
- bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
