version: '3.2'
services:
  app:
    image: clojure:lein-2.8.1-alpine
    working_dir: /home/app
    ports:
      - "3000:3000"
    volumes:
      - .:/home/app
      - type: volume
        source: dependencies
        target: /root/.m2
    command: lein run -m web.server/-main

volumes:
  dependencies:
